# Generated by Django 3.1.7 on 2021-06-20 19:59

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity_accounting_app', '0010_auto_20210620_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='_password',
            field=models.CharField(default=1, max_length=10, verbose_name='Password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inspector',
            name='is_staff',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='is_superuser',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
